### ISSUE TITLE
[Bug] Windows环境下python的open函数默认解码方式为gbk

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [Sorceresssis/TiebaScraper#10]
https://github.com/Sorceresssis/TiebaScraper/blob/929aceba3c0fe9b2091c8b3a2b443d4dd8d5a0e4/src/modules/scrape_update_module.py#L74
open函数应统一指定参数`encoding='utf-8'`，write/orjson或许也要。

**Comment by Sorceresssis** [comment]
我的系统是 `utf-8` 的, 写的时候没注意到这个问题, 这个 Bug 很严重吗。

**Comment by ZzzzzzzSkyward** [comment]
会在此处报错闪退
![Snipaste_2024-10-19_12-35-10](https://github.com/user-attachments/assets/bac6cd7a-f6ae-4bcd-88e9-cdc1b095043a)

**Comment by Sorceresssis** [comment]
改了, 下载最新的 Releases v1.3.1 试试呢。

**Comment by ZzzzzzzSkyward** [comment]
改好就好了吧，这是很常见的事
