### ISSUE TITLE
[Bug] 输入tid显示tid必须为整数

### ISSUE THREAD

**Issue by lanyuki** [Sorceresssis/TiebaScraper#11]
### Description / 描述

输入tid后显示tid必须为整数，网址如下
https://tieba.baidu.com/p/7732246743
![屏幕截图 2024-11-03 180811](https://github.com/user-attachments/assets/148c25dd-dc19-492d-ba35-6ede4214ce7d)

### Steps to reproduce / 重现步骤

输入网址的tid

**Comment by Sorceresssis** [comment]
![image](https://github.com/user-attachments/assets/90749b76-d369-46cb-903f-87a095e82447)
我这里是一切正常的。可能是设置了错误的 `BDUSS` 造成的。你可以试一试删除程序同级目录下的 `tieba_auth.json` 和 `scrape_config.json` 文件。重新启动程序，然后重新配置 BDUSS

**Comment by lanyuki** [comment]
是的，应该就是我的bduss设置错误导致的，感谢老哥
