### ISSUE TITLE
[Enhancement] 只看楼主

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [Sorceresssis/TiebaScraper#8]
### Description / 描述

有些帖子很长，多达上千页，希望只爬取楼主楼层，即通过`see_lz=1`指定的页面。

**Comment by ZzzzzzzSkyward** [comment]
在aiotieba里看到参数`only_thread_author`，添加该参数到命令行界面里即可。

**Comment by Sorceresssis** [comment]
可以，我会添加这个功能的，但我要考虑一下筛选的逻辑, 也要等个几周了。

post : 楼
subpost/Comment : 楼中楼


1. 保存所有的 post  `+`  post 下所有的 subpost
2. 保存 thread_author 的 post `+` post 下的所有 subpost
3. 保存 thread_author 的 post `+` post 下 thread_author 的 subpost
4. 保存 thread_author 和 thread_author 回复过的 post `+` post 下所有的 subpost
5. 保存 thread_author 和 thread_author 回复过的 post `+` post 下 thread_author 的 subpost

TODO: 把每次爬取的 scrape_config 写入 scrape_info.json


你可以暂时用 TiebaReader 的筛选功能。
![image](https://github.com/user-attachments/assets/2e5605cf-4a14-493a-b13b-0ca66878ca77)

**Comment by Sorceresssis** [comment]
## 更新  v1.3.1

添加了配置项 POST_FILTER_TYPE, 可以在 `命令行应用`  中 使用 `修改爬取配置` 功能进行配置修改，或者直接修改`命令行应用` 同目录下的 scrape_config.json 文件。


默认值：'all'

你所说的 `only_thread_author` 对应的是 'author_posts_with_subposts'


## POST_FILTER_TYPE 值表


| 值                                            | 说明                                                                                        |
| :-------------------------------------------- | ------------------------------------------------------------------------------------------- |
| all                                           | 所有的 post `+`  post 下的所有 subpost                                                   |
| author_posts_with_subposts                    | thread_author 的 post `+` post 下的所有 subpost                                           |
| author_posts_with_author_subposts             | thread_author 的 post `+` post 下的所有 subpost                                           |
| author_and_replied_posts_with_subposts        | thread_author 的 post 和 thread_author 回复过的 post `+` post 下所有的 subpost            |
| author_and_replied_posts_with_author_subposts | thread_author 的 post 和 thread_author 回复过的 post `+` post 下 thread_author 的 subpost |

**Comment by ZzzzzzzSkyward** [comment]
感谢！对我本人来说我只要楼主发帖即可，所以我本地在aietieba接口添加我说的参数就解决了我的需求。
